### ISSUE TITLE
Android L issue

### ISSUE THREAD

**Issue by rubinbasha** [nadavfima/GlowPadView#3]
I am developing an app and I am using your library, but with the update to android L it seems that the library crashes. I am writing part of the log to not make this comment too long. If needed i can reproduce the log and send it all to you.

Unable to start activity ComponentInfo{package/package.MyClass}: android.view.InflateException: Binary XML file line #62: Error inflating class com.fima.glowpadview.GlowPadView

Caused by: java.lang.RuntimeException: Cannot make calls to a recycled instance!
at com.fima.glowpadview.GlowPadView.<init>(GlowPadView.java:272)

**Comment by shtern** [comment]
@rubinbasha, Thank you very much for leaving a comment after finding the right way to deal with this problem!!!!
